export const GETUSERS = "GETUSERS"
export const GETPRODUCTS = "GETPRODUCTS"
export const POSTPRODUCTS = "POSTPRODUCTS"
export const POSTUSER = "POSTUSER"
export const GET_ID = "GET_ID"

export const ADD_FAV = "ADD_FAV"
export const REMOVE_FAV = "REMOVE_FAV"
export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"